const data = [
  {
    name: "Standard Hardware Database",
    label: "Standard Hardware Database",
    window_type: "standard",
    sliding_window: {
      track_2: {
        frame_name: "Track 2",
        frame_price: "100",
        re_inforcement: null,
        guide_rate: "100",
        re_enforcement: "100",
      },
      track_2_5: {
        frame_name: "Track 2.5",
        frame_price: "200",
        re_inforcement: null,
        guide_rate: "200",
        re_enforcement: "200",
      },
      track_3: {
        frame_name: "Track 3",
        frame_price: "299",
        reinforcement: null,
        guide_rate: "300",
        re_enforcement: "300",
      },
      sutter_sash: {
        frame_name: "Sutter",
        frame_price: "100",
        beating: "100",
        beating_price: "50",
        re_enforcement: "50",
        guide_rate: "50",
      },
      mess: {
        frame_name: "Mess",
        frame_price: "50",
        casecate: "40",
        re_enforcement: "10",
      },
    },
    casement_window: {
      frame: {
        frame_name: "Frame Casement",
        frame_price: "100",
        beading: "Beading casement",
        beading_price: "100",
        re_enforcement: "100",
        gasket: "100",
      },
      sutter: {
        frame_name: "Sutter",
        frame_price: "100",
        beating: "Sutter beading",
        beating_price: "200",
        re_enforcement: "100",
        gasket: "100",
      },
    },
    fixed_window: {
      frame_name: "Fixed Frame",
      frame_price: "1000",
      beading: "Beading",
      beading_price: "100",
      re_enforcement: "100",
      louver_cap: "100",
    },
    ventilation_window: {
      frame_name: "Frame ",
      frame_price: "100",
      beading: "Bed-100",
      beading_price: "100",
      re_enforcement: "100",
      gasket: "100",
    },
    glass_mess: [
      {
        type: "glass",
        model_name: "Glass 1",
        cost_per_sqft: "100",
        profile: null,
        price: null,
        id: "03417e-7f18-0f2-cd2-d50156e7e8",
      },
      {
        type: "glass",
        model_name: "Glass 2",
        cost_per_sqft: "200",
        id: "7565d2-e273-73ce-3e4d-712ea1557cf",
      },
      {
        type: "glass",
        model_name: "Glass 3",
        cost_per_sqft: "300",
        id: "77a8a-2dd1-4c7-cd7-727c3fb8858c",
      },
      {
        type: "mess",
        model_name: "Mess-100",
        cost_per_sqft: "100",
        id: "f22c67-bb14-262c-f2e2-fe26c266825",
      },
      {
        type: "mess",
        model_name: "mess-150",
        cost_per_sqft: "150",
        id: "2b3a38-e6e7-f2ee-8e10-35285627aa7",
      },
    ],
    hardware_price: {
      sliding_hardware: {
        drainage_caps: "45",
        fastner_screws: "7",
        touch_lock: "5000",
        popup_handle: "230",
        rollers: "345",
        wuoofile: "12",
        sf_stopper: "12",
        stopper: "12",
        faster_cap: "50",
        silicon: "34",
        rubber_gasket: "78",
        inter_lock: "500",
      },
      casement_hardware: {
        frictionstry: "100",
        espaq: "10",
        rubber_gasket: "10",
        casment_handle: "20",
      },
      ventilation_hardware: {
        glass_holder_cap: "240",
      },
    },
    status: 1,
    id: 1,
  },
  {
    name: "Economic Hardware Database",
    label: "Economic Hardware Database",
    window_type: "economic",
    sliding_window: {
      track_2: {
        frame_name: "Track 2",
        frame_price: "50",
        re_inforcement: null,
        guide_rate: "70",
        re_enforcement: "50",
      },
      track_2_5: {
        frame_name: "Track 2.5",
        frame_price: "200",
        re_inforcement: null,
        guide_rate: "300",
        re_enforcement: "200",
      },
      track_3: {
        frame_name: "Track 3",
        frame_price: "299",
        reinforcement: null,
        guide_rate: "700",
        re_enforcement: "300",
      },
      sutter_sash: {
        frame_name: "Sutter",
        frame_price: "50",
        beating: "400",
        beating_price: "50",
        re_enforcement: "50",
        guide_rate: "50",
      },
      mess: {
        frame_name: "Mess",
        frame_price: "10",
        casecate: "140",
        re_enforcement: "10",
      },
    },
    casement_window: {
      frame: {
        frame_name: "Frame Casement",
        frame_price: "50",
        beading: "Beading casement",
        beading_price: "50",
        re_enforcement: "50",
        gasket: "50",
      },
      sutter: {
        frame_name: "Sutter",
        frame_price: "50",
        beating: "Sutter beading",
        beating_price: "200",
        re_enforcement: "50",
        gasket: "50",
      },
    },
    fixed_window: {
      frame_name: "Fixed Frame",
      frame_price: "50",
      beading: "Beading",
      beading_price: "50",
      re_enforcement: "50",
      louver_cap: "50",
    },
    ventilation_window: {
      frame_name: "Frame ",
      frame_price: "50",
      beading: "Bed-50",
      beading_price: "50",
      re_enforcement: "50",
      gasket: "50",
    },
    glass_mess: [
      {
        type: "glass",
        model_name: "Glass 1",
        cost_per_sqft: "70",
        profile: null,
        price: null,
        id: "03417e-7f18-0f2-cd2-d50156e7e8",
      },
      {
        type: "glass",
        model_name: "Glass 2",
        cost_per_sqft: "200",
        id: "7565d2-e273-73ce-3e4d-712ea1557cf",
      },
      {
        type: "glass",
        model_name: "Glass 3",
        cost_per_sqft: "300",
        id: "77a8a-2dd1-4c7-cd7-727c3fb8858c",
      },
      {
        type: "mess",
        model_name: "Mess-70",
        cost_per_sqft: "70",
        id: "f22c67-bb14-262c-f2e2-fe26c266825",
      },
      {
        type: "mess",
        model_name: "mess-75",
        cost_per_sqft: "75",
        id: "2b3a38-e6e7-f2ee-8e10-35285627aa7",
      },
    ],
    hardware_price: {
      sliding_hardware: {
        drainage_caps: "45",
        fastner_screws: "7",
        touch_lock: "2000",
        popup_handle: "230",
        rollers: "345",
        wuoofile: "12",
        sf_stopper: "12",
        stopper: "12",
        faster_cap: "50",
        silicon: "34",
        rubber_gasket: "78",
        inter_lock: "300",
      },
      casement_hardware: {
        frictionstry: "50",
        espaq: "10",
        rubber_gasket: "10",
        casment_handle: "10",
      },
      ventilation_hardware: {
        glass_holder_cap: "100",
      },
    },
    status: 1,
  },
  {
    name: "Premium Hardware Database",
    label: "Premium Hardware Database",
    window_type: "premium",
    sliding_window: {
      track_2: {
        frame_name: "Track 2",
        frame_price: "300",
        re_inforcement: null,
        guide_rate: "300",
        re_enforcement: "300",
      },
      track_2_5: {
        frame_name: "Track 2.5",
        frame_price: "400",
        re_inforcement: null,
        guide_rate: "400",
        re_enforcement: "400",
      },
      track_3: {
        frame_name: "Track 3",
        frame_price: "299",
        reinforcement: null,
        guide_rate: "300",
        re_enforcement: "300",
      },
      sutter_sash: {
        frame_name: "Sutter",
        frame_price: "500",
        beating: "100",
        beating_price: "50",
        re_enforcement: "50",
        guide_rate: "50",
      },
      mess: {
        frame_name: "Mess",
        frame_price: "400",
        casecate: "190",
        re_enforcement: "10",
      },
    },
    casement_window: {
      frame: {
        frame_name: "Frame Casement",
        frame_price: "100",
        beading: "Beading casement",
        beading_price: "350",
        re_enforcement: "350",
        gasket: "350",
      },
      sutter: {
        frame_name: "Sutter",
        frame_price: "350",
        beating: "Sutter beading",
        beating_price: "200",
        re_enforcement: "350",
        gasket: "350",
      },
    },
    fixed_window: {
      frame_name: "Fixed Frame",
      frame_price: "5000",
      beading: "Beading",
      beading_price: "250",
      re_enforcement: "250",
      louver_cap: "250",
    },
    ventilation_window: {
      frame_name: "Frame ",
      frame_price: "100",
      beading: "Bed-100",
      beading_price: "100",
      re_enforcement: "100",
      gasket: "100",
    },
    glass_mess: [
      {
        type: "glass",
        model_name: "Glass 1",
        cost_per_sqft: "100",
        profile: null,
        price: null,
        id: "03417e-7f18-0f2-cd2-d50156e7e8",
      },
      {
        type: "glass",
        model_name: "Glass 2",
        cost_per_sqft: "200",
        id: "7565d2-e273-73ce-3e4d-712ea1557cf",
      },
      {
        type: "glass",
        model_name: "Glass 3",
        cost_per_sqft: "300",
        id: "77a8a-2dd1-4c7-cd7-727c3fb8858c",
      },
      {
        type: "mess",
        model_name: "Mess-100",
        cost_per_sqft: "100",
        id: "f22c67-bb14-262c-f2e2-fe26c266825",
      },
      {
        type: "mess",
        model_name: "mess-150",
        cost_per_sqft: "150",
        id: "2b3a38-e6e7-f2ee-8e10-35285627aa7",
      },
    ],
    hardware_price: {
      sliding_hardware: {
        drainage_caps: "45",
        fastner_screws: "7",
        touch_lock: "10000",
        popup_handle: "230",
        rollers: "3045",
        wuoofile: "12",
        sf_stopper: "12",
        stopper: "12",
        faster_cap: "50",
        silicon: "34",
        rubber_gasket: "78",
        inter_lock: "5000",
      },
      casement_hardware: {
        frictionstry: "100",
        espaq: "10",
        rubber_gasket: "100",
        casment_handle: "200",
      },
      ventilation_hardware: {
        glass_holder_cap: "2040",
      },
    },
    status: 1,
  },
];

export default data;
